WITH D0
AS
(
    SELECT A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_GROUP, A.PERIOD_ID, A.RETURN_RATE, A.MTD_RETURN_RATE, 
            COUNT(*) OVER (PARTITION BY A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_GROUP, SUBSTR(A.PERIOD_ID, 1, 7)  ORDER BY A.PERIOD_ID) MTD_DAY_PERIODS,
            COUNT(*) OVER (PARTITION BY A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_GROUP, SUBSTR(A.PERIOD_ID, 1, 4) ORDER BY A.PERIOD_ID) YTD_DAY_PERIODS,
            COUNT(*) OVER (PARTITION BY A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_GROUP ORDER BY A.PERIOD_ID) TOT_DAY_PERIODS,
            
            COUNT(CASE WHEN RETURN_RATE > 0 THEN 1 END) OVER (PARTITION BY A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_GROUP, SUBSTR(A.PERIOD_ID, 1, 7)  ORDER BY A.PERIOD_ID) MTD_WIN_DAY_PERIODS,
            COUNT(CASE WHEN RETURN_RATE > 0 THEN 1 END) OVER (PARTITION BY A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_GROUP, SUBSTR(A.PERIOD_ID, 1, 4) ORDER BY A.PERIOD_ID) YTD_WIN_DAY_PERIODS,
            COUNT(CASE WHEN RETURN_RATE > 0 THEN 1 END) OVER (PARTITION BY A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_GROUP ORDER BY A.PERIOD_ID) TOT_WIN_DAY_PERIODS
    FROM PNL_10 A
    WHERE A.PERIOD_GROUP  = 'Day'
),
D1
AS
(
    SELECT A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_GROUP, A.PERIOD_ID, A.RETURN_RATE, A.MTD_RETURN_RATE, 
            COUNT(*) OVER (PARTITION BY A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_GROUP, SUBSTR(A.PERIOD_ID, 1, 7)  ORDER BY A.PERIOD_ID) MTD_MONTH_PERIODS,
            COUNT(*) OVER (PARTITION BY A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_GROUP, SUBSTR(A.PERIOD_ID, 1, 4) ORDER BY A.PERIOD_ID) YTD_MONTH_PERIODS,
            COUNT(*) OVER (PARTITION BY A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_GROUP ORDER BY A.PERIOD_ID) TOT_MONTH_PERIODS,
            
            COUNT(CASE WHEN RETURN_RATE > 0 THEN 1 END) OVER (PARTITION BY A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_GROUP, SUBSTR(A.PERIOD_ID, 1, 7)  ORDER BY A.PERIOD_ID) MTD_WIN_MONTH_PERIODS,
            COUNT(CASE WHEN RETURN_RATE > 0 THEN 1 END) OVER (PARTITION BY A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_GROUP, SUBSTR(A.PERIOD_ID, 1, 4) ORDER BY A.PERIOD_ID) YTD_WIN_MONTH_PERIODS,
            COUNT(CASE WHEN RETURN_RATE > 0 THEN 1 END) OVER (PARTITION BY A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_GROUP ORDER BY A.PERIOD_ID) TOT_WIN_MONTH_PERIODS
    FROM PNL_10 A
    WHERE A.PERIOD_GROUP  = 'Month'
),
D2
AS
(
    SELECT A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_ID, 
                MAX(B.PERIOD_ID) MAX_PREV_MONTH_ID
    FROM D0 A
    LEFT JOIN D1 B
    ON A.ACCOUNT_ID = B.ACCOUNT_ID
    AND A.RUN_GROUP_NAME = B.RUN_GROUP_NAME
    AND SUBSTR(A.PERIOD_ID, 1, 7) > B.PERIOD_ID
    GROUP BY A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_ID
),
D3
AS
(
    SELECT A.ACCOUNT_ID, A.RUN_GROUP_NAME, A.PERIOD_ID, 
                C.MTD_WIN_DAY_PERIODS / NULLIF (C.MTD_DAY_PERIODS, 0) MTD_WIN_DAYS_RATE,
                C.YTD_WIN_DAY_PERIODS / NULLIF (C.YTD_DAY_PERIODS, 0) YTD_WIN_DAYS_RATE,
                C.TOT_WIN_DAY_PERIODS / NULLIF (C.TOT_DAY_PERIODS, 0) TOT_WIN_DAYS_RATE,
                (NVL(B.YTD_WIN_MONTH_PERIODS, 0) + CASE WHEN C.MTD_RETURN_RATE > 0 THEN 1 ELSE 0 END) / NULLIF((NVL(B.YTD_MONTH_PERIODS,0) + 1), 0) YTD_WIN_MONTHS_RATE,
                (NVL(B.TOT_WIN_MONTH_PERIODS, 0) + CASE WHEN C.MTD_RETURN_RATE > 0 THEN 1 ELSE 0 END) / NULLIF((NVL(B.TOT_MONTH_PERIODS,0) + 1), 0) TOT_WIN_MONTHS_RATE
    FROM D2 A
    JOIN D0 C
    ON A.ACCOUNT_ID = C.ACCOUNT_ID
    AND A.RUN_GROUP_NAME = C.RUN_GROUP_NAME
    AND A.PERIOD_ID = C.PERIOD_ID
    LEFT JOIN D1 B
    ON A.ACCOUNT_ID = B.ACCOUNT_ID
    AND A.RUN_GROUP_NAME = B.RUN_GROUP_NAME
    AND A.MAX_PREV_MONTH_ID = B.PERIOD_ID
)
SELECT ACCOUNT_ID, RUN_GROUP_NAME, PERIOD_ID, 
    ROUND(MTD_WIN_DAYS_RATE, 3) MTD_WIN_DAYS_RATE,
    ROUND(YTD_WIN_DAYS_RATE, 3) YTD_WIN_DAYS_RATE,
    ROUND(TOT_WIN_DAYS_RATE, 3) TOT_WIN_DAYS_RATE,
    ROUND(YTD_WIN_MONTHS_RATE, 3) YTD_WIN_MONTHS_RATE,
    ROUND(TOT_WIN_MONTHS_RATE, 3) TOT_WIN_MONTHS_RATE
FROM D3
WHERE ACCOUNT_ID = 'SIM-19-HIGH'
ORDER BY PERIOD_ID DESC
    
    
    
;
